# Generated by Django 4.2.5 on 2023-11-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('location', models.CharField(blank=True, max_length=25, null=True)),
                ('avilability', models.BooleanField(blank=True, default=False, null=True)),
                ('breed', models.TextField(blank=True, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('health', models.CharField(choices=[('H', 'Healthy'), ('I', 'injure'), ('U', 'Unhealthy')], default=1, max_length=1)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('species', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
