# Generated by Django 4.2.5 on 2023-11-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=122)),
                ('applicant', models.CharField(max_length=122)),
                ('pet_name', models.CharField(max_length=122)),
                ('data', models.CharField(max_length=122)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('D', 'Decline')], default='P', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='AdoptionApplication',
        ),
    ]
