# Generated by Django 4.2.5 on 2023-11-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_application_delete_adoptionapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
