# Generated by Django 4.2.5 on 2023-11-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_application_application_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.IntegerField(default=-99, primary_key=True, serialize=False),
        ),
    ]
