# Generated by Django 4.2.5 on 2023-12-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='data',
            field=models.CharField(max_length=12),
        ),
    ]
