# Generated by Django 4.1.5 on 2023-12-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_application_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='data',
        ),
        migrations.RemoveField(
            model_name='application',
            name='pet_name',
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_id',
            field=models.AutoField(default=-99, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='desc',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
