# Generated by Django 4.2.5 on 2023-12-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_pet_appllication_delete_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
